### PR TITLE
Fix keystone tooltip

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LeoLeal** [comment]
Hi.
Can you elaborate what's wrong with Keystone Tooltips?

**Comment by ghost** [comment]
On Korean client, strsplit(":", link) returns wrong value for third affixID.
Because contained ":" in keystone displayed name.
I'm sorry, didn't tell reason.

also, tried to tweak.

**Comment by LeoLeal** [comment]
I will have to test against the other locales first. and will accept the merge as soon as I can.

**Comment by LeoLeal** [comment]
Tell you that: I'm accepting and will test It and fix as needed. Then Ill release a version.

**Comment by LeoLeal** [comment]
Your patch broke the third affix for the English client (Fortified is not in the Tooltip now). Will have to fix this.

**Comment by LeoLeal** [comment]
I made a more elegant fix that makes less changes to the code.

Thanks for letting me know about this issue. :) 
An update is coming as soon as CurseForge approves the file upload.

**Comment by ghost** [comment]
Thank you.
I'll wait your superior patch.

**Pull request merged**
